Repository suryanshsingh2001/mockly, pull requests merged in 2024-10, with the labels that each got.

#19 Feature - shadow options
  components/shadow-manager.tsx
  components/shared/Editor.tsx
  components/ui/popover.tsx
  package-lock.json
  package.json
Labels: question, hacktoberfest-accepted

#22 moving padding-x from body to individual pages for better stability
  app/(public)/privacy/page.tsx
  app/(public)/terms/page.tsx
  app/layout.tsx
  app/not-found.tsx
  components/layout/LandingPage.tsx
  components/shared/Editor.tsx
  components/shared/NotAvailable.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted, ui

#20 adding input fields for custom screen size and validations
  components/shared/Editor.tsx
  components/shared/ValidatedInput.tsx
  components/shared/types.ts
  components/shared/utils.ts
Labels: bug, enhancement, question, hacktoberfest-accepted, ui

#25 Fix/removing NaN for shadow
  components/shadow-manager.tsx
  components/shared/Editor.tsx
Labels: question, hacktoberfest-accepted

#26 Add more setting for text styling
  components/shared/Editor.tsx
  components/text-manager.tsx
  components/ui/toggle-group.tsx
  components/ui/toggle.tsx
  lib/constants.ts
  package-lock.json
  package.json
Labels: hacktoberfest, hacktoberfest-accepted

#28 Use offset when setting cursor position
  components/shared/Editor.tsx
Labels: enhancement, hacktoberfest-accepted, rebase

#32 [Feature Request] Add FAQs section in landing page
  components/layout/LandingPage.tsx
  components/sections/FAQSection.tsx
  lib/constants.ts
Labels: documentation, hacktoberfest-accepted, feature, ui

#31 Feature/video
  app/editor/page.tsx
  app/layout.tsx
  app/video/beta/page.tsx
  components/layout/LandingPage.tsx
  components/screen-recorder.tsx
  components/sections/CTASection.tsx
  components/sections/FAQSection.tsx
  components/sections/FeatureSection.tsx
  components/shadow-manager.tsx
  components/shared/Editor.tsx
  components/shared/VideoEditor.tsx
  components/text-manager.tsx
  components/ui/slider.tsx
  components/ui/toggle-group.tsx
  components/ui/toggle.tsx
  lib/constants.ts
  package-lock.json
  package.json
Labels: question, hacktoberfest-accepted, feature

#37 fixed small bug in the editor, added scrollable property
  components/shared/Editor.tsx
  components/ui/scroll-area.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: bug, question, hacktoberfest, hacktoberfest-accepted

#39 Feature/custom background
  components/shared/Editor.tsx
  tailwind.config.ts
Labels: documentation, hacktoberfest-accepted, feature

#35 Added text Wrapping Feature, where the text wraps after reaching max …
  components/shared/Editor.tsx
Labels: question, triage
